name: rust-hello-world-infra
description: Infrastructure for Rust Hello World ECR
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
